### ISSUE TITLE
ENOENT on Lab v 5.10.0

### ISSUE THREAD

**Issue by hofan41** [wtcross/grunt-lab#21]
If you try running grunt-lab in windows with lab 5.10.0 it will break with ENOENT. 

5.9.0 works.

**Comment by jlouazel** [comment]
I think it's because lab 5.10 is run from lab/bin instead of lab/.bin in 5.9.  If you change ```.bin``` by ```bin``` in line 67 of ```grunt-lab/tasks/lab.js```, it will work.

**Comment by wtcross** [comment]
@jlouazel resolved this with #23
